import Head from "next/head";
import Layout from "../layouts";
import Hero from "components/hero-section";
import Kitchen from "components/kitchen-section";
import Blog from "components/blog-section";
import Contact from "components/contact-section";

export default function Home() {
    return (
        <>
            <Head>
                <title>Munchies - Home</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <Hero />
                <Kitchen />
                <Blog />
                <Contact />
            </Layout>
        </>
    );
}
